project_id = "fzmyesdhiskuytgkaggi"

[functions.generate-text]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.generate-video]
verify_jwt = true

[functions.ai-story-assist]
verify_jwt = true

[functions.generate-story-cover]
verify_jwt = true
